finnapp/finnapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('stocks/', include('stocks.urls')),
    path('admin/', admin.site.urls),
]

finnapp/stocks/urls.py
from django.urls import path
from . import views

app_name = 'stocks'
urlpatterns = [
	path('', views.index, name='index'),
	path('<int:symbol_id>/detail/', views.detail, name='detail')
]

finnapp/stocks/models.py
from django.db import models

# Create your models here.
# Remember the three-step guide to making model changes:

 #    Change your models (in models.py).
 #    Run python manage.py makemigrations to create migrations for those changes
 #    Run python manage.py migrate to apply those changes to the database.



class data_vendor(models.Model):
	name = models.CharField(max_length=200)
	website_url = models.CharField(max_length=200, default=None, null=True, blank=True)
	created_date = models.DateTimeField('created_date')
	last_updated_date = models.DateTimeField('last_updated_date')



class symbol(models.Model):
	ticker = models.CharField(max_length=200)
	instrument = models.CharField(max_length=200)
	name = models.CharField(max_length=200)
	sector = models.CharField(max_length=200)
	currency = models.CharField(max_length=200, default=None, null=True, blank=True)
	created_date = models.DateTimeField('created_date')
	last_updated_date = models.DateTimeField('last_updated_date')


class daily_data(models.Model):
	data_vendor_id = models.ForeignKey(data_vendor, on_delete=models.PROTECT)
	symbol_id = models.ForeignKey(symbol, on_delete=models.PROTECT)
	created_date = models.DateTimeField('created_date')
	last_updated_date = models.DateTimeField('last_updated_date')
	date_price = models.DateTimeField('date_price')
	open_price = models.DecimalField(max_digits=20, decimal_places=10, default=0)
	high_price = models.DecimalField(max_digits=20, decimal_places=10, default=0)
	low_price = models.DecimalField(max_digits=20, decimal_places=10, default=0)
	close_price = models.DecimalField(max_digits=20, decimal_places=10, default=0)
	adj_close_price = models.DecimalField(max_digits=20, decimal_places=10, default=0)
	volume = models.IntegerField(default=0)

finnapp/stocks/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import symbol, daily_data
import statistics

import datetime

# Create your views here.


def index(request):
	# Design vystupu je hard-coded in python, je lepsie pouzit template system
	'''
	symbols_list = symbol.objects.order_by('-ticker')
	output = '<br>'.join([s.name for s in symbols_list])
	return HttpResponse(output)
	'''
	# Vyuzitie template
	symbols_list = symbol.objects.order_by('ticker')
	context = {
		'symbols_list': symbols_list
	}
	return render(request, 'stocks/index.html', context)


def detail(request, symbol_id):
	# Ak nie je zvoleny param, zobraz posledne dva roky dodnes
	date_from = request.POST['date_from'] if 'date_from' in request.POST else str((datetime.datetime.now() - datetime.timedelta(days=365*3)).date())
	date_to = request.POST['date_to'] if 'date_to' in request.POST else str(datetime.datetime.now().date())

	symbol_info = get_object_or_404(symbol, id=symbol_id)
	data = daily_data.objects.filter(symbol_id=symbol_id, date_price__range=[date_from, date_to]).order_by('date_price')
	if data:
		aggr = {
			'open_price_mean': statistics.mean([d.open_price for d in data]),
			'close_price_mean': statistics.mean([d.close_price for d in data]),
			'high_price_mean': statistics.mean([d.high_price for d in data]),
			'low_price_mean': statistics.mean([d.low_price for d in data]),
			'adj_close_price_mean': statistics.mean([d.close_price for d in data]),
			'volume_mean': statistics.mean([d.volume for d in data])
		}
	else:
		aggr = {}

	return render(request, 'stocks/details_bt.html', {'symbol_info': symbol_info, 'data': data, 'aggr': aggr})

finnapp/stocks/templates/stocks/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Bootstrap 4, from LayoutIt!</title>

    <meta name="description" content="Source code generated using layoutit.com">
    <meta name="author" content="LayoutIt!">

    {% load static %}
    <link href="{% static 'stocks/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'stocks/style.css' %}" rel="stylesheet">

  </head>
  <body>
  	{% block content %}
  	{% endblock %}
  </body>
</html>

finnapp/stocks/templates/stocks/detail.html
	<table border="1">
		<tr>
			<th>Ticker</th>
			<th>Instrument</th>
			<th>Name</th>
			<th>Sector</th>
			<th>Currency</th>
			<th>Last update</th>
		</tr>

		<tr>
			<td>{{ symbol_info.ticker }}</td>
			<td>{{ symbol_info.instrument }}</td>
			<td>{{ symbol_info.name }}</td>
			<td>{{ symbol_info.sector }}</td>
			<td>{{ symbol_info.currency }}</td>
			<td>{{ symbol_info.last_updated_date }}</td>
		</tr>		
	</table>	

	<br>
	<form action="{% url 'stocks:detail' symbol_info.id %}" method="post">
		{% csrf_token %}
		<label for="date_from">From</label>
		<input type="date" name="date_from">
		<label for="date_to">To</label>
		<input type="date" name="date_to">
		<input type="submit" value="Submit">
	</form>

	<br>
{% if data %}
	<table border="1">
		<tr>
			<th>Date</th>
			<th>Open</th>
			<th>Close</th>
			<th>High</th>
			<th>Low</th>
			<th>Adjacent</th>
			<th>Volume</th>
		</tr>
		{% for d in data%}
		<tr>
			<td>{{ d.date_price | date}}</td>
			<td>{{ d.open_price | floatformat:3 }}</td>
			<td>{{ d.close_price | floatformat:3 }}</td>
			<td>{{ d.high_price | floatformat:3 }}</td>
			<td>{{ d.low_price | floatformat:3 }}</td>
			<td>{{ d.adj_close_price | floatformat:3 }}</td>
			<td>{{ d.volume }}</td>
		</tr>
		{% endfor %}

		<tr>
			<th>Mean</th>
			<td>{{ aggr.open_price_mean | floatformat:3}}</td>
			<td>{{ aggr.close_price_mean | floatformat:3}}</td>
			<td>{{ aggr.high_price_mean | floatformat:3}}</td>
			<td>{{ aggr.low_price_mean | floatformat:3}}</td>
			<td>{{ aggr.adj_close_price_mean | floatformat:3}}</td> 
			<td>{{ aggr.volume_mean | floatformat:0}}</td> 
		</tr>
	</table>
{% else %}
	<p>No data found</p>
{% endif%}

finnapp/stocks/templates/stocks/details_bt.html
{% extends 'stocks/base.html' %}

{% block content %}
    <div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<h1 class="text-left">
			 	{{ symbol_info.name }}
			</h1>
			<table class="table">
				<thead>
					<tr>
						<th>
							Ticker
						</th>
						<th>
							Instrument
						</th>
						<th>
							Sector
						</th>
						<th>
							Currency
						</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>{{ symbol_info.ticker }}</td>
						<td>{{ symbol_info.instrument }}</td>
						<td>{{ symbol_info.sector }}</td>
						<td>{{ symbol_info.currency }}</td>
					</tr>
				</tbody>
			</table>
			<div class="row">
				<div class="col-md-6">
					<h3>
						41.74
					</h3>
					<h4>
						-0.42 (-1,42%)
					</h4>
					<p>March 1, 2020, 10:57 a.m.</p>
				</div>
				<div class="col-md-6">
					 
					<button type="button" class="btn btn-success btn-normal">
						Buy
					</button> 
					<button type="button" class="btn btn-normal btn-danger">
						Sell
					</button>
				</div>
			</div>

			<div class="row">
				<div class="col-md-6">
					<form  action="{% url 'stocks:detail' symbol_info.id %}" method="post">
						{% csrf_token %}
						<div class="form-group">
							<label for="date_from">From</label>
							<input type="date" class="form-control" name="date_from">
						</div>
						<div class="form-group">
							<label for="date_to">To</label>
							<input type="date" class="form-control" name="date_to">
						</div>
						
						<button type="submit" class="btn btn-primary">
							Submit
						</button>
					</form>
				</div>
				<div class="col-md-6">
					<img id="plot" src="https://miro.medium.com/max/1526/1*_CRdtGZ-qQ1flJkDz2kLiQ.png">
				</div>
			</div>

			{% if data %}
			<table class="table table-striped">
				<thead>
					<tr>
						<th>
							Date
						</th>
						<th>
							Open
						</th>
						<th>
							Close
						</th>
						<th>
							High
						</th>
						<th>
							Low
						</th>
						<th>
							Adjacent
						</th>
						<th>
							Volume
						</th>
					</tr>
				</thead>
				<tbody>
					{% for d in data%}
					<tr>
						<td>{{ d.date_price | date}}</td>
						<td>{{ d.open_price | floatformat:3 }}</td>
						<td>{{ d.close_price | floatformat:3 }}</td>
						<td>{{ d.high_price | floatformat:3 }}</td>
						<td>{{ d.low_price | floatformat:3 }}</td>
						<td>{{ d.adj_close_price | floatformat:3 }}</td>
						<td>{{ d.volume }}</td>
					</tr>
					{% endfor %}					
				</tbody>
			</table>
			{% endif %}
		</div>
	</div>
</div>
{% endblock %}

finnapp/stocks/templates/stocks/index.html
{% if symbols_list %}
	<ul>
		{% for symbol in symbols_list %}
			<!-- <li><a href='/stocks/{{ symbol.id }}/detail'>{{ symbol.name }}</a></li> -->
			<li><a href="{% url 'stocks:detail' symbol.id %}">{{ symbol.name }}</a></li>
		{% endfor %}
	</ul>
{% else %}
	<p>No symbols found</p>
{% endif %}